# Generated by Django 5.0.1 on 2024-02-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_type',
            field=models.CharField(blank=True, choices=[('electrician', 'Electrician'), ('mishtry', 'Mishtry'), ('color_work', 'Color Work')], max_length=255, null=True),
        ),
    ]
