# Generated by Django 5.0.1 on 2024-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_people_people_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='assigned_people',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
